data: 
  dataset: zinc_standard_agent  # dataset name
  # dataset_dir: data
  batch_size: 32              # batch size
  num_workers: 4               # number of workers for data loading
  mask_edge: True
  mask_rate1: 0.15
  mask_rate2: 0.30

model:
  emb_dim: 300
  num_tokens: 512
  pred_edge: True              # whether to predict edge in VQ-VAE
  gnn:
    num_layer: 5
    JK: last
    drop_ratio: 0.5
  vq_encoder:
    num_layer: 5


train:  # Training params
  task_type: pretrain
  device: 'cuda'                    # device to use for training
  max_epochs: 60                    # *total number of epochs, 200
  learning_rate: 0.001              # *learning rate
  lr_patience: 20
  lr_decay: 0.5
  min_lr: 1e-6
  weight_decay: 0.